let catalog = [
     {
          id: 0,
          title: "Xiaomi Earbuds Basic 2",
          price: 43,
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//5f7303737e3e0.webp",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 1,
          title: "HUAWEI Band 6 (Black)",
          price: 57,
          img: "https://assets.asaxiy.uz/product/items/desktop/8f6…6954e8bb0161430c20210921120056797762oKaPgQSqy.jpg",
          overview: "These headphones are perfect for running or any other physical activity. The oval body fits easily into the ear, where it is practically not felt and does not cause discomfort even with prolonged use.",
          categories: ["phones", "gadgets"],
     },
     {
          id: 3,
          title: "Apple iPhone 11 128 Gb, Black",
          price: 1105,
          img: "https://avatars.mds.yandex.net/get-mpic/4262452/img_id3167434503299217434.jpeg/orig",
          overview: "The functional and stylish smartphone Apple iPhone 11 in a metal case is able to provide not only everyday communication and entertainment, but also productive work. To do this, it is equipped with a powerful 6-core Apple A13 Bionic processor that supports the smooth operation of all components, as well as a 4 GB RAM module, which provides for quick switching between open applications and the ability to play games. The main (12; 12 Mp) and front (12 Mp) cameras will allow you to create photo masterpieces. The image on the screen of the Apple iPhone 11 smartphone with a diagonal of 6.1 inches has amazing detail and color reproduction. Oleophobic coating eliminates severe screen contamination. The case of the smartphone has a high degree of dust and moisture protection (IP68), which ensures efficient and long-term operation of the device. The non-removable 3110 mAh battery supports wireless charging, making the process easier and faster.",
          categories: ["phones", "apple"],
     },
     {
          id: 4,
          title: "Apple iPhone 12 mini 128 Gb, White",
          price: 998,
          img: "https://avatars.mds.yandex.net/get-mpic/5218438/img_id3284878141399346796.png/5hq",
          overview: "Apple iPhone 12 mini is a super-powerful smartphone in an ultra-small format. Inside the compact case, a whole set of advanced features has been registered. The lightning-fast A14 Bionic processor delivers incredible performance. The amazing Super Retina XDR display pleases with a juicy picture. The camera system surprises with image quality, and MagSafe charging eliminates the hassle of cables. Dolby Vision video recording is a strong trump card of the device. The stories are very realistic. You can edit videos directly on your gadget in the iMovie application. The Face ID recognition system works like clockwork. Apple iPhone 12 mini is a miniature smartphone with enormous functionality. This is the dynamic user's choice.",
          categories: ["phones", "apple"],
     },
     {
          id: 5,
          title: "Apple iPhone SE 2020 64 Gb",
          price: 412.35,
          img: "https://avatars.mds.yandex.net/get-mpic/5425309/img_id8041282677742130028.png/x248_trim",
          overview: "iPhone SE is the most powerful compact iPhone ever, packed with cutting-edge technologies. A13 Bionic is the fastest processor in the iPhone, delivering the best performance for apps, games and photography. Portrait mode and six lighting effects for studio-quality photos. Next-generation Smart HDR technology for incredible detail, even in bright and dark areas of the frame. Cinematic quality 4K video. And the most advanced features of iOS. With long battery life and water resistance, everything you love about iPhone comes in a surprisingly small package.",
          categories: ["phones", "apple"],
     },
     {
          id: 6,
          title: "Apple iPhone Xs",
          price: 574.97,
          img: "https://avatars.mds.yandex.net/get-mpic/1912364/img_id2264559175193642486.jpeg/x248_trim",
          overview: "iPhone XS features a 5.8-inch Super Retina HDR display. OLED panels provide the best color reproduction, deep blacks and impressive brightness. With improved FaceID technology, you can securely unlock your iPhone, sign in to your app accounts, and pay for purchases with just a glance. The A12 Bionic processor with next-generation Neural Engine uses machine learning technology to deliver incredible experiences for photography, gaming, augmented reality and more. And the stunning 12MP Dual Camera with Portrait mode, Portrait Lighting, enhanced bokeh and the all-new Depth feature gives you a whole new way to take portraits.",
          categories: ["phones", "apple"],
     },
     {
          id: 7,
          title: "Apple Macbook Pro Late 2021 ",
          price: 2423.58,
          img: "https://avatars.mds.yandex.net/get-marketpic/1583642/picbb1618e273a3278330e77f9bc0dbcb4f/120x160",
          overview: "The Apple MacBook Pro 14 (2021) is the most powerful MacBook Pro ever, powered by the high-tech M1 Pro chip. The memory bandwidth is more than 200 GB / s, and there is also the possibility of connecting two monitors. The MacBook Pro 14 (2021) features a stunning Liquid Retina XDR display with extreme dynamic range and superb contrast.",
          categories: ["computer", "apple"],
     },
     {
          id: 8,
          title: "Apple MacBook Pro 16",
          price: "3849.61",
          img: "https://assets.asaxiy.uz/product/main_image/webp/desktop//602e45c1e38e8.webp",
          overview: "The new MacBook Pro is our most powerful laptop, built for world-changing and pushing the boundaries. With an impressive 16-inch Retina display, blazingly fast processor, next-generation graphics card, the highest battery life ever on a MacBook Pro, the new Magic Keyboard and massive storage, this is the best professional laptop for the most serious professional. Specs Type: laptop Operating system: macOS Processor Processor: Intel Core i7 9750H 2600 MHz Number of processor cores: 6 L3 cache: 12 MB Memory Memory: 16 GB DDR4 2666 MHz Image Screen: 16-inch, 3072x1920 widescreen Screen type: IPS Display Backlight: LED Graphics Card Type: Integrated, Discrete, Discrete, and Integrated Video Processor: AMD Radeon Pro 5300M Video Memory: 4 GB Video Memory Type: GDDR6 Storage Devices Drive Configuration: SSD Total Drive Capacity: 512 GB Optical Drive: No Connectivity Wireless: Wi-Fi IEEE 802.11ac, Bluetooth 5.0 Interfaces: Thunderbolt 3 x 4, microphone/headphones Combo Power Battery life: 11 hours Battery capacity: 100 Wh Battery type: Li-Pol Input devices Pointing devices: Touchpad Number of keyboard keys : 66 Keyboard backlight: yes Touch Bar: yes Sound Built-in speakers: yes Built-in subwoofer: yes Built-in microphone he: yes Optional Webcam: yes Fingerprint scanner: yes Features: metal case Dimensions (LxWxT): 357.9x245.9x16.2 mm Weight: 2 kg",
          categories: ["computer", "apple"],
     },
     {
          id: 9,
          title: "Apple MacBook Pro 13 Mid 2018",
          price: 1496.43,
          img: "https://avatars.mds.yandex.net/get-mpic/4393885/img_id8583047582289821123.jpeg/x248_trim",
          overview: "13.3 Laptop Apple MacBook Pro 13 Mid 2018 (2560x1600, Intel Core i5 2.3 GHz, RAM 8 GB, SSD 512 GB), MR9V2RU/A, silver",
          categories: ["computer", "apple"],
     },
     {
          id: 10,
          title: "16 ASUS StudioBook H7600HM",
          price: 3017.93,
          img: "https://avatars.mds.yandex.net/get-mpic/5245452/img_id2242488603442486682.jpeg/7hq",
          overview: "16, 3840x2400, 2.40kg, Windows 11 Pro",
          categories: ["computer", "asus"],
     },
     {
          id: 11,
          title: "15.6 ASUS TUF Gaming F15",
          price: 1054.06,
          img: "https://avatars.mds.yandex.net/get-mpic/5221145/img_id2057303444764211296.jpeg/x248_trim",
          overview: "15.60, 1920x1080, 2.30Kg, Windows 10 Home",
          categories: ["computer", "asus"],
     },
     {
          id: 12,
          title: "14 Lenovo IdeaPad",
          price: 541.26,
          img: "https://avatars.mds.yandex.net/get-mpic/5227339/img_id6329274375650094646.jpeg/x248_trim",
          overview: "Run the most complex programs, run them simultaneously, play the latest AAA games - the IdeaPad 3 Gen 6 (14) can handle it all with AMD processors. Enjoy top-notch speed and intelligence for a simple, easy-to-use laptop, and stunning picture quality.",
          categories: ["computer", "lenova"],
     },
     {
          id: 13,
          title: "14 HUAWEI MateBook D 14 2021",
          price: 588.19,
          img: "https://avatars.mds.yandex.net/get-mpic/5332815/img_id599237706642247539.png/x248_trim",
          overview: "14 1920x1080, 1.38kg, Windows 10 Home",
          categories: ["computer", "huawei"],
     },
     {
          id: 14,
          title: "Acer Extensa 15 EX215",
          price: 515.42,
          img: "https://avatars.mds.yandex.net/get-mpic/1537623/img_id8339231750727610101.png/x248_trim",
          overview: "14 1920x1080, 1.38kg, Windows 10 Home",
          categories: ["computer", "acer"],
     },
     {
          id: 15,
          title: "HP 15-eg0099ur",
          price: 714.96,
          img: "https://avatars.mds.yandex.net/get-mpic/4950407/img_id1898531585317262486.png/x248_trim",
          overview: "Display diagonal: 15.6 LED. Display resolution: 1920x1080 FHD. Screen matrix type: TFT IPS. Processor: Intel Core i3. Number of processor cores: 4. Processor series: 1125G4. Processor frequency: 2000 MHz. Processor frequency (Turbo mode) : 3700 MHz Graphics Card Type: Integrated Graphics Card: Intel UHD Graphics RAM Type: DDR4 RAM: 8 Gb Storage Type: SSD SSD Capacity: 512 GB Wi-Fi: Yes BlueTooth: Yes USB 3.0: 2 USB-Type-C: 1 HDMI: Yes Audio: combo out (headphones) / in (microphone) (3.5 mm) Installed OS: Windows 10 Home 64-bit Sound system: Yes Built-in speakers: 2 x 2W Fingerprint scanner: Yes Webcam: Yes Keyboard backlight: Yes Weight: 1.75 kg Warranty: 1 year",
          categories: ["computer", "hp"],
     },
     {
          id: 16,
          title: "Acer Extensa 15 EX215",
          price: 515.42,
          img: "https://avatars.mds.yandex.net/get-mpic/1537623/img_id8339231750727610101.png/x248_trim",
          overview: "14 1920x1080, 1.38kg, Windows 10 Home",
          categories: ["computer", "acer"],
     },
     {
          id: 17,
          title: "Samsung Galaxy S21 Ultra 5G",
          price: 1342.82,
          img: "https://avatars.mds.yandex.net/get-mpic/1537623/img_id8339231750727610101.png/x248_trim",
          overview: "Samsung presents to your attention a new flagship that can surprise both ordinary users and its competitors with its advanced functionality - Samsung Galaxy S21 Ultra. Now for those who like to work with a pen. New reliable display. The Samsung Galaxy S21 Ultra is equipped with a 1440x3200 AMOLED display and Corning Gorilla Glass Victus, which boasts improved double protection against scratches and bumps. The front surface also has a special surface that is resistant to scratches. The updated camera is even closer to the ideal. Speaking of the Galaxy S21 Ultra, one cannot fail to mention its camera, which has been improved in every way. All four cameras now feature 10x optical zoom and autofocus for even richer close-ups, as well as 8K video recording at any focal length. Nice addition, and most importantly - functional. The Samsung Galaxy S21 Ultra now supports the branded S Pen, which makes typing and performing other functions on your smartphone more intuitive and easier, keeping your screen intact from scratches, marks and fingerprints. Performance at the forefront. The Galaxy S21 Ultra is powered by the latest Exynos 2100 octa-core SoC with up to 16GB of RAM. Its power is enough to satisfy the desires of the most demanding players, while maintaining the graphics quality at the highest possible level.",
          categories: ["phones", "samsung"],
     },
     {
          id: 18,
          title: "Samsung Galaxy Z Flip3 8/256Gb",
          price: 948.49,
          img: "https://avatars.mds.yandex.net/get-mpic/4937511/img_id904183233304253356.png/x248_trim",
          overview: "The Samsung Galaxy Z Flip3 is a new technological reimagining of the flip phone with a host of improvements. A new high-quality camera and an advanced display, an improved design and a disclosure mechanism - all this and much more, the novelty is ready to please you right now.",
          categories: ["phones", "samsung"],
     },
     {
          id: 19,
          title: "Samsung Galaxy A52 4/128Gb",
          price: 281.25,
          img: "https://avatars.mds.yandex.net/get-mpic/5366650/img_id5150216314890197601.png/x248_trim",
          overview: "Samsung never ceases to win the hearts of users and releases a new smartphone - Samsung Galaxy A52, which continues its path from the legendary bestseller Galaxy 51. Just as perfect and just as affordable, Samsung Galaxy A52 is ready to become your next hit.",
          categories: ["phones", "samsung"],
     },
     {
          id: 20,
          title: "Samsung Galaxy S20 FE",
          price: 460.31,
          img: "https://avatars.mds.yandex.net/get-mpic/5221857/img_id3970673557616715132.jpeg/9hq",
          overview: "The Samsung Galaxy S20 FE is the flagship you've been waiting for. Based on the feedback and wishes of users, the company is presenting you with an update that is saturated with a variety of technologies for your vivid impressions.",
          categories: ["phones", "samsung"],
     },
     {
          id: 21,
          title: "Xiaomi 11 Lite 5G NE 8/128 ГБ",
          price: 313.74,
          img: "https://avatars.mds.yandex.net/get-mpic/5210379/img_id3422786426357764400.png/x248_trim",
          overview: "Android 11 6.55 (2400x1080), Full HD, AMOLED",
          categories: ["phones", "xiaomi"],
     },
     {
          id: 22,
          title: "Xiaomi Poco M4 Pro 5G",
          price: 217.43,
          img: "https://avatars.mds.yandex.net/get-mpic/5376959/img_id5871150949110117334.png/x248_trim",
          overview: "The POCO M4 Pro 5G features the same classic POCO design that fans know and love, with three cool color options. It fits so well in your hand that you never want to put it down.",
          categories: ["phones", "xiaomi"],
     },
     {
          id: 23,
          title: "Xiaomi Redmi 9 NFC",
          price: 176.37,
          img: "https://avatars.mds.yandex.net/get-mpic/4615030/img_id1957978681175755298.jpeg/x248_trim",
          overview: "General characteristics Standard: GSM 900/1800/1900, 3G, 4G LTE, VoLTE Type: smartphone OS version at launch: Android 10 Case type: classic Number of SIM cards: 2 SIM card type: nano SIM Contactless payment Dimensions (HxWxD): 16.33x7.7x0.91 cm Weight: 198g",
          categories: ["phones", "xiaomi"],
     },
     {
          id: 24,
          title: "Xiaomi Redmi Note 9 Pro",
          price: 268.46,
          img: "https://avatars.mds.yandex.net/get-mpic/4397502/img_id7040435686711884343.jpeg/x248_trim",
          overview: "The Redmi Note series has never been afraid of performance comparisons, and Redmi Note 9 Pro continues this tradition: a powerful and fast smartphone ideal for work, study and entertainment. The novelty has a side fingerprint, which makes unlocking extremely fast! The screen and cover of Redmi Note 9 Pro are made of Gorilla Glass 5. Perhaps the main change in the display of the novelty is the rejection of screen cutouts. Now Redmi Note 9 Pro has received a fashionable peephole embedded in the screen. Otherwise, it's still the same IPS-matrix with a resolution of 1080 x 2400 pixels. The screen has grown again - now its diagonal is 6.67 inches. Redmi Note 9 Pro is equipped with a quad-camera system, the performance of which is not inferior to the flagship offerings on the market. The main camera has a resolution of 64 MP for high-quality shooting, the other cameras allow you to capture a panorama with the ultra wide-angle camera, close objects with the macro camera, and achieve a beautiful portrait.",
          categories: ["phones", "xiaomi"],
     },
     {
          id: 25,
          title: "Samsung Galaxy S10",
          price: 613.79,
          img: "https://avatars.mds.yandex.net/get-mpic/4599566/img_id517451220347569287.jpeg/x248_trim",
          overview: "The Samsung Galaxy S10 smartphone is a powerful model that incorporates the most innovative achievements of the Samsung Galaxy line. The immersive 6.1-inch bezel-less display supports 3040x1440 resolution. It will immerse you in your favorite movies, series, games and other video content. Capture your own photos and videos with the dual rear camera and advanced 10MP front camera. Enjoy a bright and contrasting picture with excellent color reproduction. A powerful processor with 8 cores will allow you to work productively even with resource-intensive applications. Support for LTE will provide you with high-speed Internet, wherever you are. Your data will be completely safe thanks to the ultrasonic fingerprint scanner, as well as the innovative face scanner.",
          categories: ["phones", "samsung"],
     },
]